### ISSUE TITLE
Missing a lot of scanner options

### ISSUE THREAD

**Issue by i3jjnc68emm** [Squalr/Squalr#244]
- Search for unknown value
- Binary values
- String values
- Unicode string values
- AOB
- AOB with pattern / wildcard support
- ALL data type (combines byte / int32 / float / double etc)

Search for unknown and AOB should have top priority immo. Unknown value is what you searc hfor in about 50% of all scans. AOB is absolutely required for scripting and working with differnet game versions.
I've seen you plan since 2016 to add AOB search, is that really that difficult to add that you didn't worked it out yet or do you believe it's not that important? As it actually is.

**Comment by zcanann** [comment]
Unknown value the same as the 'collect values' scan -- this already exists. It works differently than CE because this program is not supposed to be an exact clone of Cheat Engine.

Collect Values allows you to do the following:
- If it's the first scan, it's the same as an unknown value scan
- If it is not the first scan, it allows you to re-start from your current scan in case you forget what is going on

Imagine trying to find the Y position in a game:
- 1) Start => Collect values (unknown value scan)
- 2) Move up hill => Scan for increased value
- 3) Move down hill => Scan for decreased value
- 4) {repeat 2-3 several times}
- 5) If you forget if the previous scan was increased/decreased, in CE you would have to start this process again
- 6) However in Squalr, simply hit "Collect Values" again.
- 7) {continue to repeat steps 2-3}

AOB is important but I've been busy. If anyone wants to take this on -- the project is open source and well commented.
Strings are pretty low priority for game hacking, they are usually only cosmetic changes
Binary is medium priority and it will be awhile before I get to that
ALL data type would be nice, but also medium priority for me

**Comment by ghost** [comment]
@zcanann is an AOB scanner with wildcard supported still needed? I'd be happy to try and integrate one I just wrote.
